### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by alu0101130026** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupoj#1]
Buenos días, estamos teniendo problemas con Github Actions, he seguido los pasos del vídeo del campus para instalarlo pero una vez realizado, si entro en la pestaña actions me salta un error en ese trabajo, diciéndome que hay algún problema con el lock o que debería de estar, pero nosotros no lo tenemos incluido en el repositorio. @esegredo @amarrerod @alu0101130026 @alu0101215310

**Comment by esegredo** [comment]
Hola, buenas tardes.

En las notas al vídeo correspondiente se les indica dos opciones para solventar el problema anterior. ¿Han leído dichas notas al vídeo disponibles en el aula virtual?

Saludos.

**Comment by alu0101130026** [comment]
Hemos solucionado el error, pero ahora el problema que tenemos es que hay veces que aparece el tick verde como que todo ha ido correctamente pero otras veces no. @esegredo @amarrerod @alu0101130026 @alu0101215310

**Comment by esegredo** [comment]
¿Cuando hacen un `npm install` en el proyecto, ¿obtienen algún tipo de error? El flujo de trabajo está yendo mal cuando intentan ejecutar eso.

Borren el fichero package-lock.json del proyecto, vuelvan a hacer un npm install, y suban el nuevo fichero package-lock.json al repositorio, por probar una alternativa.

Saludos.
